#service 
apiVersion: v1
kind: Service
metadata:
   #the Serivce Name- it should match with the lable name of the deployment 
  name: argocd-react
spec:
  #type of the service
  type: NodePort
  selector:
    app: argocd-react
  ports:
  - port: 8888
    targetPort: 3000
    protocol: TCP
    nodePort: 31000